// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/alphax-s550-pnp/connectors/custom_firmware.yaml
#pragma once

Gpio GENERATED_OUTPUTS[] = {
	Gpio::F14, // Ignition 1
	Gpio::D7, // Ignition 2
	Gpio::G9, // Ignition 3
	Gpio::F15, // Ignition 4
	Gpio::G10, // Ignition 5
	Gpio::F12, // Ignition 6
	Gpio::F13, // Ignition 7
	Gpio::G11, // Ignition 8
	Gpio::B8, // Injector 1
	Gpio::E3, // Injector 2
	Gpio::E5, // Injector 3
	Gpio::C13, // Injector 4
	Gpio::B9, // Injector 5
	Gpio::E2, // Injector 6
	Gpio::E4, // Injector 7
	Gpio::E6, // Injector 8
	Gpio::C8, // VVT 1 (Bank1 Exhaust)
	Gpio::C9, // VVT 2 (Bank1 Intake)
	Gpio::C6, // VVT 3 (Bank2 Exhaust)
	Gpio::C7, // VVT 4 (Bank2 Intake)
	Gpio::I7, // ETB1 PWM
	Gpio::I5, // ETB1 Direction
	Gpio::I4, // ETB1 Disable
	Gpio::I6, // ETB2 PWM
	Gpio::E1, // ETB2 Direction
	Gpio::E0, // ETB2 Disable
	Gpio::C4, // Main Relay
	Gpio::E12, // Fuel Pump Relay
	Gpio::E14, // Fan 1 Relay
	Gpio::B0, // Fan 2
	Gpio::E13, // AC Clutch Relay
	Gpio::E11, // Alternator Control
	Gpio::H12, // Boost Solenoid
	Gpio::D9, // Tachometer Output
	Gpio::G2, // Purge Solenoid
	Gpio::G3, // Cutout Control
	Gpio::G4, // Diff Pump Speed
	Gpio::G5, // Vent Solenoid
	Gpio::G7, // GENLI
	Gpio::B1, // Starter Relay
	Gpio::C5, // IMRC 1
	Gpio::A7, // IMRC 2
	Gpio::D8, // DPO 1
	Gpio::D10, // DPO 2
	Gpio::E10, // Fuel FSO / PWR EN
	Gpio::B10, // SMCS High
	Gpio::F2, // ADC MUX Select (PF2)
	Gpio::G0, // Comms LED
	Gpio::G1, // Run LED
	Gpio::E7, // Warn LED
	Gpio::E8, // Error LED
// "Ignition 1",
// "Ignition 2",
// "Ignition 3",
// "Ignition 4",
// "Ignition 5",
// "Ignition 6",
// "Ignition 7",
// "Ignition 8",
// "Injector 1",
// "Injector 2",
// "Injector 3",
// "Injector 4",
// "Injector 5",
// "Injector 6",
// "Injector 7",
// "Injector 8",
// "VVT 1 (Bank1 Exhaust)",
// "VVT 2 (Bank1 Intake)",
// "VVT 3 (Bank2 Exhaust)",
// "VVT 4 (Bank2 Intake)",
// "ETB1 PWM",
// "ETB1 Direction",
// "ETB1 Disable",
// "ETB2 PWM",
// "ETB2 Direction",
// "ETB2 Disable",
// "Main Relay",
// "Fuel Pump Relay",
// "Fan 1 Relay",
// "Fan 2",
// "AC Clutch Relay",
// "Alternator Control",
// "Boost Solenoid",
// "Tachometer Output",
// "Purge Solenoid",
// "Cutout Control",
// "Diff Pump Speed",
// "Vent Solenoid",
// "GENLI",
// "Starter Relay",
// "IMRC 1",
// "IMRC 2",
// "DPO 1",
// "DPO 2",
// "Fuel FSO / PWR EN",
// "SMCS High",
// "ADC MUX Select (PF2)",
// "Comms LED",
// "Run LED",
// "Warn LED",
// "Error LED",
}
