# Combine the related files for a specific platform and MCU.

# Target ECU board design
BOARDCPPSRC = $(BOARD_DIR)/board_configuration.cpp

ifeq ($(PROJECT_CPU),ARCH_STM32F7)
	DDEFS += -DLUA_RX_MAX_FILTER_COUNT=96
endif

# Add them all together
DDEFS += -DFIRMWARE_ID=\"protorico-econoline\" $(VAR_DEF_ENGINE_TYPE)

#Knock is available on F4 and F7
ifeq ($(PROJECT_CPU),ARCH_STM32H7)
	# Default H743 linker script is not compatible
	LDSCRIPT = $(PROJECT_DIR)/hw_layer/ports/stm32/stm32h7/STM32H723xG_ITCM64k.ld
	# Do not use HSE autodetection
	DDEFS += -DSTM32_HSECLK=20000000
	DDEFS += -DENABLE_AUTO_DETECT_HSE=FALSE
	# We are limited in flash
	DDEFS += -DRAMDISK_INVALID
	DEBUG_LEVEL_OPT = -Os -ggdb -g
else
	#Knock is available on F4 and F7 only
	DDEFS += -DEFI_SOFTWARE_KNOCK=TRUE -DSTM32_ADC_USE_ADC3=TRUE
endif

# EGT chip
DDEFS += -DEFI_MAX_31855=TRUE

DDEFS += -DHELLEN_BOARD_ID_DEBUG

# Skip board type resistor detection and use static board ID
DDEFS += -DHW_HELLEN_SKIP_BOARD_TYPE=TRUE
DDEFS += -DSTATIC_BOARD_ID=BOARD_ID_UAEFI_B


DDEFS += -DDIAG_5VP_PIN=Gpio::C12

DDEFS += -DSTM32_ICU_USE_TIM1=TRUE -DSTM32_PWM_USE_TIM1=FALSE
DDEFS += -DEFI_SENT_SUPPORT=TRUE

ONBOARD_MEMS_TYPE=LIS2DH12

# This board uses the 100-pin MCU module
include $(BOARDS_DIR)/hellen/hellen-common100.mk

# Drop some Lua functionality to save RAM
DDEFS += -DWITH_LUA_CONSUMPTION=FALSE
DDEFS += -DWITH_LUA_PID=FALSE
DDEFS += -DWITH_LUA_STOP_ENGINE=FALSE

# Space saving flags from hellen154hyundai
DDEFS += -DEFI_HPFP=FALSE
DDEFS += -DEFI_WIDEBAND_FIRMWARE_UPDATE=FALSE
DDEFS += -DEFI_EMBED_INI_MSD=FALSE
DDEFS += -DEFI_LOGIC_ANALYZER=FALSE
DDEFS += -DEFI_ENGINE_SNIFFER=FALSE
DDEFS += -DEFI_ENGINE_EMULATOR=FALSE
DDEFS += -DEFI_TOOTH_LOGGER=FALSE

# Override USART2 pins to match hardware: PD5 is TX, PD6 is RX
PRIMARY_COMMUNICATION_PORT_USART2 = -DTS_PRIMARY_UxART_PORT=SD2 -DEFI_TS_PRIMARY_IS_SERIAL=TRUE -DSTM32_SERIAL_USE_USART2=TRUE
PRIMARY_COMMUNICATION_PORT_USART2 += -DEFI_CONSOLE_TX_BRAIN_PIN=Gpio::D5 -DEFI_CONSOLE_RX_BRAIN_PIN=Gpio::D6
DDEFS += $(PRIMARY_COMMUNICATION_PORT_USART2)


ifeq ($(PROJECT_CPU),ARCH_STM32F7)
 DDEFS += -DUSB_DESCRIPTOR_STRING_CONTENT="'r', 0, 'u', 0, 's', 0, 'E', 0, 'F', 0, 'I', 0, ' ', 0, 'u', 0, 'a', 0, 'E', 0, 'F', 0, 'I', 0, ' ', 0, 'P', 0, 'R', 0, 'O', 0"
else
 DDEFS += -DUSB_DESCRIPTOR_STRING_CONTENT="'r', 0, 'u', 0, 's', 0, 'E', 0, 'F', 0, 'I', 0, ' ', 0, 'u', 0, 'a', 0, 'E', 0, 'F', 0, 'I', 0"
endif

DDEFS += -DBOARD_SERIAL="\"000000000000000000000000\""

# Bootloader CAN configuration (CAND1 on PD0/PD1)
DDEFS += -DBOOT_COM_CAN_CHANNEL_INDEX=0
DDEFS += -DOPENBLT_CAN_RX_PORT=GPIOD
DDEFS += -DOPENBLT_CAN_RX_PIN=0
DDEFS += -DOPENBLT_CAN_TX_PORT=GPIOD
DDEFS += -DOPENBLT_CAN_TX_PIN=1

# Added by Board Configuration Editor
DDEFS += -DEFI_BURST_KNOCK=TRUE
DDEFS += -DEFI_CRANKING_NO_SPARK=TRUE
DDEFS += -DEFI_ELECTRONIC_THROTTLE_BODY=FALSE
DDEFS += -DEFI_MALFUNCTION_INDICATOR=TRUE
DDEFS += -DEFI_MISFIRE_DETECTION=TRUE
DDEFS += -DEFI_OFF_IDLE_RPM_ADDER=TRUE
DDEFS += -DEFI_STORAGE_SD=FALSE
DDEFS += -DEFI_TEXT_LOGGING=FALSE
DDEFS += -DEFI_UART_GPS=FALSE
DDEFS += -DEFI_USE_COMPRESSED_INI_MSD=FALSE
DDEFS += -DEFI_VVT_PID=FALSE
DDEFS += -DEFI_WOT_ENRICHMENT=TRUE

# Added by Board Configuration Editor
DDEFS += -DEFI_ENGINE_STATE_MACHINE=TRUE

# No real CLT sensor on this Ford Modular V8 -- estimate CLT from the CHT sensor.
# F4 defaults this off (only F7/H7 default it on) -- see cht_clt_estimator.h.
DDEFS += -DEFI_CHT_CLT_ESTIMATOR=TRUE

# TCU support
DDEFS += -DEFI_TCU=TRUE
