// content of this file was generated by TuneCanTool.java

static void cannedsparkDwellValues() {
}

static void canneddwellVoltageCorrValues() {
}

static void cannedidleAdvanceBins() {
}

static void cannedcltIdleRpm() {
#if CLT_CURVE_SIZE == 16
	static const float hardCodedcltIdleRpm[16] = {1860.0, 1860.0, 1800.0, 1700.0, 1660.0, 1600.0, 1560.0, 1500.0, 1500.0, 1460.0, 1460.0, 1440.0, 1400.0, 1400.0, 1500.0, 1600.0};
	copyArray(config->cltIdleRpm, hardCodedcltIdleRpm);
#endif // CLT_CURVE_SIZE
}

static void cannedidleAdvance() {
}

static void cannedignitionRpmBins() {
#if (IGN_RPM_COUNT == 16) && (IGN_LOAD_COUNT == 16)
	static const float hardCodedignitionRpmBins[16] = {800.0, 1000.0, 1300.0, 1600.0, 2000.0, 2500.0, 3000.0, 3600.0, 4000.0, 4400.0, 4900.0, 5300.0, 5800.0, 6200.0, 7100.0, 8000.0};
	copyArray(config->ignitionRpmBins, hardCodedignitionRpmBins);
#endif
}

static void cannedignitionLoadBins() {
#if (IGN_RPM_COUNT == 16) && (IGN_LOAD_COUNT == 16)
	static const float hardCodedignitionLoadBins[16] = {15.0, 27.0, 33.0, 45.0, 57.0, 69.0, 81.0, 93.0, 105.0, 129.0, 157.0, 186.0, 214.0, 243.0, 271.0, 300.0};
	copyArray(config->ignitionLoadBins, hardCodedignitionLoadBins);
#endif
}

static void cannedveRpmBins() {
#if (VE_LOAD_COUNT == 16) && (VE_RPM_COUNT == 16)
	static const float hardCodedveRpmBins[16] = {800.0, 1000.0, 1300.0, 1600.0, 2000.0, 2500.0, 3000.0, 3600.0, 4000.0, 4400.0, 4900.0, 5300.0, 5800.0, 6200.0, 7100.0, 8000.0};
	copyArray(config->veRpmBins, hardCodedveRpmBins);
#endif
}

static void cannedveLoadBins() {
#if (VE_LOAD_COUNT == 16) && (VE_RPM_COUNT == 16)
	static const float hardCodedveLoadBins[16] = {15.0, 27.0, 33.0, 45.0, 57.0, 69.0, 81.0, 93.0, 105.0, 129.0, 157.0, 186.0, 214.0, 243.0, 271.0, 300.0};
	copyArray(config->veLoadBins, hardCodedveLoadBins);
#endif
}

static void cannedboostRpmBins() {
#if (BOOST_LOAD_COUNT == 8) && (BOOST_RPM_COUNT == 8)
	static const float hardCodedboostRpmBins[8] = {0.0, 1100.0, 2300.0, 3400.0, 4600.0, 5700.0, 6900.0, 8000.0};
	copyArray(config->boostRpmBins, hardCodedboostRpmBins);
#endif
}

static void cannedpedalToTpsRpmBins() {
	static const float hardCodedpedalToTpsRpmBins[8] = {0.0, 1100.0, 2300.0, 3400.0, 4600.0, 5700.0, 6900.0, 8000.0};
	copyArray(config->pedalToTpsRpmBins, hardCodedpedalToTpsRpmBins);
}

static void cannedcltIdleCorr() {
#if CLT_IDLE_TABLE_CLT_SIZE == 16
//todo hardCodedcltIdleCorr	static const float hardCodedcltIdleCorr[16] = {1.1, 1.1, 0.9333, 0.9333, 0.9333, 0.8333, 0.6333, 0.6333, 0.5, 0.5, 0.4667, 0.3, 0.3, 0.3, 0.3, 0.3};
//todo	copyArray(config->cltIdleCorr, hardCodedcltIdleCorr);
#endif // CLT_IDLE_TABLE_CLT_SIZE
}

static void cannedcltCrankingCorr() {
}
