# Combine the related files for a specific platform and MCU.

# Target ECU board design
BOARDCPPSRC = $(BOARD_DIR)/board_configuration.cpp


# Add them all together
DDEFS += -DEFI_SOFTWARE_KNOCK=TRUE -DSTM32_ADC_USE_ADC3=TRUE

DDEFS += -DADC_MUX_PIN=Gpio::B3

include $(BOARDS_DIR)/hellen/hellen-common144.mk

ifeq ($(PROJECT_CPU),ARCH_STM32F7)
	DDEFS += -DCH_DBG_ENABLE_ASSERTS=FALSE
	DDEFS += -DENABLE_PERF_TRACE=FALSE
else ifeq ($(PROJECT_CPU),ARCH_STM32F4)
    # This board has trigger scope hardware!
    DDEFS += -DTRIGGER_SCOPE
    # serial ports only on F4
	DDEFS += $(PRIMARY_COMMUNICATION_PORT_USART2)
else
$(error Unsupported PROJECT_CPU [$(PROJECT_CPU)])
endif

DDEFS += -DSTATIC_BOARD_ID=STATIC_BOARD_ID_ALPHAX_8CHAN

DDEFS += -DHW_HELLEN_8CHAN=1
DDEFS += -DLUA_STM32_STANDBY=1

# AlphaX custom features (TS page 5)
DDEFS += -DEFI_VVT_COMPENSATION=TRUE
DDEFS += -DEFI_ADVANCED_FUEL_PUMP=TRUE
DDEFS += -DEFI_EXHAUST_CUTOUT=TRUE
DDEFS += -DEFI_DOWNSHIFT_BLIPPER=TRUE
DDEFS += -DEFI_ENGINE_STATE_MACHINE=TRUE
DDEFS += -DEFI_MISFIRE_DETECTION=TRUE
DDEFS += -DEFI_CLUTCH_DELAY_VALVE=TRUE
DDEFS += -DEFI_LAUNCH_POWER_RAMP=TRUE
DDEFS += -DEFI_BURST_KNOCK=TRUE
DDEFS += -DEFI_WOT_ENRICHMENT=TRUE
DDEFS += -DEFI_SPORT_PEDAL=TRUE
DDEFS += -DEFI_AC_PRESSURE_FAN=TRUE
DDEFS += -DEFI_OFF_IDLE_RPM_ADDER=TRUE
DDEFS += -DEFI_LUA_LIMITER=TRUE
