meta: config/boards/hellen_meta.h

pins:
  - pin: IGN1
    meta: H144_IGN_1
    class: outputs
    type: ign
    function: Ignition Coil 1 (STM32_IGN1)

  - pin: IGN2
    meta: H144_IGN_2
    class: outputs
    type: ign
    function: Ignition Coil 2 (STM32_IGN2)

  - pin: IGN3
    meta: H144_IGN_3
    class: outputs
    type: ign
    function: Ignition Coil 3 (STM32_IGN3)

  - pin: IGN4
    meta: H144_IGN_4
    class: outputs
    type: ign
    function: Ignition Coil 4 (STM32_IGN4)

  - pin: IGN5
    meta: H144_IGN_5
    class: outputs
    type: ign
    function: Ignition Coil 5 (STM32_IGN5)

  - pin: IGN6
    meta: H144_IGN_6
    class: outputs
    type: ign
    function: Ignition Coil 6 (STM32_IGN6)

  - pin: IGN7
    meta: H144_IGN_7
    class: outputs
    type: ign
    function: Ignition Coil 7 (STM32_IGN7)

  - pin: IGN8
    meta: H144_IGN_8
    class: outputs
    type: ign
    function: Ignition Coil 8 (STM32_IGN8)

  - pin: OUT_INJ1
    id: D3
    class: outputs
    type: ls
    function: Injector 1 (STM32_INJ1)

  - pin: OUT_INJ2
    id: A9
    class: outputs
    type: ls
    function: Injector 2 (STM32_INJ2)

  - pin: OUT_INJ3
    id: D11
    class: outputs
    type: ls
    function: Injector 3 (STM32_INJ3)

  - pin: OUT_INJ4
    id: D10
    class: outputs
    type: ls
    function: Injector 4 (STM32_INJ4)

  - pin: OUT_INJ5
    id: D2
    class: outputs
    type: ls
    function: Injector 5 (STM32_INJ5)

  - pin: OUT_INJ6
    id: A8
    class: outputs
    type: ls
    function: Injector 6 (STM32_INJ6)

  - pin: OUT_INJ7
    id: D15
    class: outputs
    type: ls
    function: Injector 7 (STM32_INJ7)

  - pin: OUT_INJ8
    id: D12
    class: outputs
    type: ls
    function: Injector 8 (STM32_INJ8)

  - pin: IN_D1
    meta: H144_IN_D_1
    class: event_inputs
    function: Crank Trigger (STM32_CRANK)

  - pin: IN_D2
    meta: H144_IN_D_2
    class: event_inputs
    function: Cam 1 Position (STM32_CAM1)

  - pin: IN_D3
    meta: H144_IN_D_3
    class: event_inputs
    function: Cam 2 Position (STM32_CAM2)

  - pin: IN_D4
    meta: H144_IN_D_4
    class: event_inputs
    function: Cam 3 Position (STM32_CAM3)

  - pin: UART8_RX
    meta: H144_UART8_RX
    class: event_inputs
    function: Cam 4 Position (STM32_CAM4)

  - pin: UART2_RX
    meta: H144_UART2_RX
    class: event_inputs
    function: Vehicle Speed Sensor (STM32_VSS)

  - pin: UART2_TX
    meta: H144_UART2_TX
    class: event_inputs
    function: Flex Fuel Input (STM32_FLEX)

  - pin: LED2
    id: G1
    class: outputs
    type: ls
    function: Main Relay (STM32_MREL)

  - pin: OUT_PWM6
    meta: H144_OUT_PWM6
    class: outputs
    type: ls
    function: Fuel Pump Relay (STM32_FP)

  - pin: SPI2_MISO
    id: B14
    class: outputs
    type: ls
    function: A/C Clutch Relay (STM32_ACREL)

  - pin: SPI3_CS
    id: A15
    class: outputs
    type: ls
    function: Cooling Fan 1 Relay (STM32_FAN)

  - pin: SPI3_MISO
    id: C11
    class: outputs
    type: ls
    function: Cooling Fan 2 Relay (STM32_FAN2)

  - pin: OUT_PWM5
    meta: H144_OUT_PWM5
    class: outputs
    type: ls
    function: Alternator Control (STM32_ALT)

  - pin: OUT_PWM1
    meta: H144_OUT_PWM1
    class: outputs
    type: ls
    function: VVT Solenoid 1 (STM32_VVT1)

  - pin: OUT_PWM2
    meta: H144_OUT_PWM2
    class: outputs
    type: ls
    function: VVT Solenoid 2 (STM32_VVT2)

  - pin: USBID
    id: A10
    class: outputs
    type: ls
    function: VVT Solenoid 3 (STM32_VVT3)

  - pin: LED4
    id: E8
    class: outputs
    type: ls
    function: VVT Solenoid 4 (STM32_VVT4)

  - pin: A25
    meta: H144_IN_RES3
    class: outputs
    type: ls
    function: Boost Control (STM32_BOOST)

  - pin: OUT_PWM3
    meta: H144_OUT_PWM3
    class: outputs
    type: ls
    function: ETB H-Bridge Direction (STM32_ETB_DIR)

  - pin: OUT_PWM4
    meta: H144_OUT_PWM4
    class: outputs
    type: ls
    function: ETB H-Bridge PWM (STM32_ETB_PWM)

  - pin: SPI2_MOSI
    id: B15
    class: outputs
    type: ls
    function: ETB H-Bridge Disable (STM32_ETB_DIS)

  - pin: A9
    meta: H144_IN_MAP1
    class: analog_inputs
    type: av
    function: MAP Sensor (STM32_OMAP)

  - pin: A10
    meta: H144_IN_MAP2_DIGITAL
    class: switch_inputs
    function: Start Request Switch (STM32_START_REQ)

  - pin: A11
    meta: H144_IN_CLT
    class: analog_inputs
    type: av
    function: Coolant Temperature (CLT_OUT)

  - pin: A12
    meta: H144_IN_AUX1_ANALOG
    class: analog_inputs
    type: av
    function: Throttle Position B (TPSB_OUT)

  - pin: A13
    meta: H144_IN_AUX2_ANALOG
    class: analog_inputs
    type: av
    function: Oil Pressure Sensor (OILPRESS_OUT)

  - pin: A14
    meta: H144_IN_IAT
    class: analog_inputs
    type: av
    function: Intake Air Temperature (IAT_OUT)

  - pin: A15
    meta: H144_IN_O2S
    class: analog_inputs
    type: av
    function: Knock Sensor (STM32_KNOCK)

  - pin: A17
    meta: H144_IN_TPS
    class: analog_inputs
    type: av
    function: Throttle Position A (TPSA_OUT)

  - pin: A18
    meta: H144_IN_PPS
    class: analog_inputs
    type: av
    function: Accelerator Pedal A (PPSA_OUT)

  - pin: A19
    meta: H144_IN_O2S2_DIGITAL
    class: switch_inputs
    function: Clutch Switch (STM32_CLUTCHU)

  - pin: A20
    meta: H144_IN_AUX3_ANALOG
    class: analog_inputs
    type: av
    function: Accelerator Pedal B (PPSB_OUT)

  - pin: A21
    meta: H144_IN_AUX4_ANALOG
    class: analog_inputs
    type: av
    function: Cylinder Head Temperature (CHT_OUT)

  - pin: A22
    meta: H144_IN_MAP3
    class: analog_inputs
    type: av
    function: A/C Pressure Sensor (AC_PRESS_OUT)

  - pin: A24
    meta: H144_IN_CRANK
    class: switch_inputs
    function: Brake Switch (STM32_BRAKE)

info:
  cid: main
  title: alphax-s197-v2
  name: S197 Mustang Pinout
  directory: hellen/alphax-s197-v2
