// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/alphax-s197-v2/connectors/connectors.yaml
#pragma once

Gpio GENERATED_OUTPUTS[] = {
	Gpio::H144_IGN_1, // Ignition Coil 1
	Gpio::H144_IGN_2, // Ignition Coil 2
	Gpio::H144_IGN_3, // Ignition Coil 3
	Gpio::H144_IGN_4, // Ignition Coil 4
	Gpio::H144_IGN_5, // Ignition Coil 5
	Gpio::H144_IGN_6, // Ignition Coil 6
	Gpio::H144_IGN_7, // Ignition Coil 7
	Gpio::H144_IGN_8, // Ignition Coil 8
	Gpio::D3, // Injector 1
	Gpio::A9, // Injector 2
	Gpio::D11, // Injector 3
	Gpio::D10, // Injector 4
	Gpio::D2, // Injector 5
	Gpio::A8, // Injector 6
	Gpio::D15, // Injector 7
	Gpio::D12, // Injector 8
	Gpio::D7, // Main Relay
	Gpio::H144_OUT_PWM6, // Fuel Pump Relay
	Gpio::B14, // A/C Clutch Relay
	Gpio::A15, // Cooling Fan 1 Relay
	Gpio::C11, // Cooling Fan 2 Relay
	Gpio::H144_OUT_PWM5, // Alternator Control
	Gpio::H144_OUT_PWM1, // VVT Solenoid 1
	Gpio::H144_OUT_PWM2, // VVT Solenoid 2
	Gpio::A10, // VVT Solenoid 3
	Gpio::E8, // VVT Solenoid 4
	Gpio::E9, // Boost Control
	Gpio::H144_OUT_PWM3, // ETB H-Bridge Direction
	Gpio::H144_OUT_PWM4, // ETB H-Bridge PWM
	Gpio::B15, // ETB H-Bridge Disable
// "Ignition Coil 1",
// "Ignition Coil 2",
// "Ignition Coil 3",
// "Ignition Coil 4",
// "Ignition Coil 5",
// "Ignition Coil 6",
// "Ignition Coil 7",
// "Ignition Coil 8",
// "Injector 1",
// "Injector 2",
// "Injector 3",
// "Injector 4",
// "Injector 5",
// "Injector 6",
// "Injector 7",
// "Injector 8",
// "Main Relay",
// "Fuel Pump Relay",
// "A/C Clutch Relay",
// "Cooling Fan 1 Relay",
// "Cooling Fan 2 Relay",
// "Alternator Control",
// "VVT Solenoid 1",
// "VVT Solenoid 2",
// "VVT Solenoid 3",
// "VVT Solenoid 4",
// "Boost Control",
// "ETB H-Bridge Direction",
// "ETB H-Bridge PWM",
// "ETB H-Bridge Disable",
}
