// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/alphax-s197-v2/connectors/connectors.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char* getBoardSpecificPinName(brain_pin_e brainPin) {
	switch (brainPin) {
		case Gpio::A10:
			return "VVT Solenoid 3";
		case Gpio::A15:
			return "Cooling Fan 1 Relay";
		case Gpio::A6:
			return "Clutch Switch";
		case Gpio::A8:
			return "Injector 6";
		case Gpio::A9:
			return "Injector 2";
		case Gpio::B0:
			return "Reverse Switch";
		case Gpio::B1:
			return "Brake Switch";
		case Gpio::B14:
			return "A/C Clutch Relay";
		case Gpio::B15:
			return "ETB H-Bridge Disable";
		case Gpio::B8:
			return "Ignition Coil 6";
		case Gpio::B9:
			return "Ignition Coil 7";
		case Gpio::C1:
			return "Start Request Switch";
		case Gpio::C11:
			return "Cooling Fan 2 Relay";
		case Gpio::C13:
			return "Ignition Coil 1";
		case Gpio::C6:
			return "VVT Solenoid 2";
		case Gpio::C7:
			return "ETB H-Bridge Direction";
		case Gpio::C8:
			return "ETB H-Bridge PWM";
		case Gpio::C9:
			return "Alternator Control";
		case Gpio::D10:
			return "Injector 4";
		case Gpio::D11:
			return "Injector 3";
		case Gpio::D12:
			return "Injector 8";
		case Gpio::D13:
			return "VVT Solenoid 1";
		case Gpio::D14:
			return "Fuel Pump Relay";
		case Gpio::D15:
			return "Injector 7";
		case Gpio::D2:
			return "Injector 5";
		case Gpio::D3:
			return "Injector 1";
		case Gpio::D5:
			return "Flex Fuel Input";
		case Gpio::D6:
			return "Vehicle Speed Sensor";
		case Gpio::D7:
			return "Main Relay";
		case Gpio::E0:
			return "Cam 4 Position";
		case Gpio::E12:
			return "Crank Trigger";
		case Gpio::E13:
			return "Cam 1 Position";
		case Gpio::E14:
			return "Cam 2 Position";
		case Gpio::E15:
			return "Cam 3 Position";
		case Gpio::E2:
			return "Ignition Coil 5";
		case Gpio::E3:
			return "Ignition Coil 4";
		case Gpio::E4:
			return "Ignition Coil 3";
		case Gpio::E5:
			return "Ignition Coil 2";
		case Gpio::E6:
			return "Ignition Coil 8";
		case Gpio::E8:
			return "VVT Solenoid 4";
		case Gpio::E9:
			return "Boost Control";
		default:
			return nullptr;
	}
	return nullptr;
}
