

# Target ECU board design
BOARDCPPSRC = $(BOARD_DIR)/board_configuration.cpp

# todo? hopefully we've used the right chips? include $(PROJECT_DIR)/hw_layer/ports/stm32/2mb_flash.mk

DDEFS += -DEFI_MC33816=TRUE
DDEFS += -DBOARD_TLE9104_COUNT=4

DDEFS += -DSTM32_ICU_USE_TIM1=TRUE -DSTM32_PWM_USE_TIM1=FALSE
DDEFS += -DEFI_SENT_SUPPORT=TRUE

# we have hellen board id BOARD_ID_GDI4CHAN_A

DDEFS += -DHW_HELLEN_4K_GDI=1
DDEFS += -DLUA_STM32_STANDBY=1

include $(BOARDS_DIR)/hellen/hellen-common-mega144.mk

# AlphaX custom features (TS page 5)
DDEFS += -DEFI_VVT_COMPENSATION=TRUE
DDEFS += -DEFI_VVT_ADVANCED_MODE=TRUE
DDEFS += -DEFI_ADVANCED_FUEL_PUMP=TRUE
DDEFS += -DEFI_EXHAUST_CUTOUT=TRUE
DDEFS += -DEFI_DOWNSHIFT_BLIPPER=TRUE
DDEFS += -DEFI_UPSHIFT_RPM_HOLD=TRUE
DDEFS += -DEFI_ENGINE_STATE_MACHINE=TRUE
DDEFS += -DEFI_MISFIRE_DETECTION=TRUE
DDEFS += -DEFI_CLUTCH_DELAY_VALVE=TRUE
DDEFS += -DEFI_LAUNCH_POWER_RAMP=TRUE
DDEFS += -DEFI_BURST_KNOCK=TRUE
DDEFS += -DEFI_WOT_ENRICHMENT=TRUE
DDEFS += -DEFI_SPORT_PEDAL=TRUE
DDEFS += -DEFI_AC_PRESSURE_FAN=TRUE
DDEFS += -DEFI_OFF_IDLE_RPM_ADDER=TRUE
DDEFS += -DEFI_LUA_LIMITER=TRUE

