/**
 * @file efifeatures.h
 *
 * @date Mar 7, 2014
 * @author Andrey Belomutskiy, (c) 2012-2020
 */

#pragma once

#define EFI_ENABLE_ASSERTS TRUE

#define EFI_ANTILAG_SYSTEM TRUE

#define EFI_TUNER_STUDIO TRUE

#define EFI_AUX_VALVES TRUE

#define EFI_EMULATE_POSITION_SENSORS TRUE

#define EFI_VEHICLE_SPEED TRUE

#define EFI_ENGINE_SNIFFER TRUE

#define FULL_SD_LOGS TRUE

#define EFI_SENT_SUPPORT TRUE

#define EFI_PRINTF_FUEL_DETAILS TRUE

#define ENABLE_PERF_TRACE FALSE

#define EFI_TOOTH_LOGGER TRUE

#define EFI_LAUNCH_CONTROL TRUE

#define EFI_LTFT_CONTROL TRUE

#define EFI_DYNO_VIEW TRUE

#define EFI_BOOST_CONTROL TRUE

#define EFI_IDLE_CONTROL TRUE

#define EFI_ELECTRONIC_THROTTLE_BODY TRUE

#define SPARK_EXTREME_LOGGING TRUE

#define EFI_GPIO_HARDWARE TRUE

#define FUEL_MATH_EXTREME_LOGGING TRUE

#define EFI_DETAILED_LOGGING FALSE

#define DEBUG_INTERPOLATION TRUE

#define EFI_TEXT_LOGGING TRUE

#define EFI_HISTOGRAMS FALSE

#define EFI_CLI_SUPPORT FALSE

#define EFI_SIGNAL_EXECUTOR_ONE_TIMER FALSE
#define EFI_SIGNAL_EXECUTOR_SLEEP FALSE

#define EFI_SHAFT_POSITION_INPUT TRUE
#define EFI_ENGINE_CONTROL TRUE

#define EFI_ANALOG_SENSORS TRUE

#define EFI_BOARD_TEST FALSE

#define EFI_MAP_AVERAGING TRUE

#define EFI_LUA TRUE

#define EFI_HPFP TRUE

#define EFI_MAIN_RELAY_CONTROL TRUE

#define EFI_MISFIRE_DETECTION TRUE

#define EFI_ALTERNATOR_CONTROL TRUE

#define EFI_TCU TRUE

#define ROTATIONAL_IDLE_CONTROLLER TRUE

#define EFI_ADVANCED_FUEL_PUMP TRUE

#define EFI_VVT_COMPENSATION TRUE
#define EFI_VVT_ADVANCED_MODE TRUE

#define EFI_EXHAUST_CUTOUT TRUE

// AlphaX custom subsystems (config in TS page 5) — enabled for unit tests.
#define EFI_DOWNSHIFT_BLIPPER TRUE
#define EFI_UPSHIFT_RPM_HOLD TRUE
#define EFI_ENGINE_STATE_MACHINE TRUE
#define EFI_MISFIRE_DETECTION TRUE
#define EFI_CLUTCH_DELAY_VALVE TRUE
#define EFI_LAUNCH_POWER_RAMP TRUE
#define EFI_ROLLING_LAUNCH TRUE
#define EFI_BURST_KNOCK TRUE
#define EFI_WOT_ENRICHMENT TRUE
#define EFI_SPORT_PEDAL TRUE
#define EFI_OIL_LIFE_MONITOR TRUE
#define EFI_GHOST_CAM TRUE
#define EFI_AC_PRESSURE_FAN TRUE
#define EFI_OFF_IDLE_RPM_ADDER TRUE
#define EFI_LUA_LIMITER TRUE
#define EFI_CHECK_ENGINE_TRIGGERING TRUE
#define EFI_CHT_CLT_ESTIMATOR TRUE
