# Combine the related files for a specific platform and MCU.

# Target ECU board design
BOARDCPPSRC = $(BOARD_DIR)/board_configuration.cpp


# This board has trigger scope hardware!
DDEFS += -DTRIGGER_SCOPE

export USE_OPENBLT=yes

# Add them all together
DDEFS += -DEFI_SOFTWARE_KNOCK=TRUE -DSTM32_ADC_USE_ADC3=TRUE

# pretty temporary
DDEFS += -DDISABLE_PIN_STATE_VALIDATION=TRUE

ONBOARD_MEMS_TYPE=LIS2DH12

include $(BOARDS_DIR)/hellen/hellen-common144.mk

DDEFS += $(PRIMARY_COMMUNICATION_PORT_USART2)

DDEFS += -DSTATIC_BOARD_ID=STATIC_BOARD_ID_ALPHAX_2CHAN

# let 2chan start asap
DDEFS += -DBOOT_BACKDOOR_ENTRY_TIMEOUT_MS=0

# AlphaX custom features (TS page 5)
DDEFS += -DEFI_VVT_COMPENSATION=TRUE
DDEFS += -DEFI_ADVANCED_FUEL_PUMP=TRUE
DDEFS += -DEFI_EXHAUST_CUTOUT=TRUE
DDEFS += -DEFI_DOWNSHIFT_BLIPPER=TRUE
DDEFS += -DEFI_ENGINE_STATE_MACHINE=TRUE
DDEFS += -DEFI_MISFIRE_DETECTION=TRUE
DDEFS += -DEFI_CLUTCH_DELAY_VALVE=TRUE
DDEFS += -DEFI_LAUNCH_POWER_RAMP=TRUE
DDEFS += -DEFI_BURST_KNOCK=TRUE
DDEFS += -DEFI_WOT_ENRICHMENT=TRUE
DDEFS += -DEFI_SPORT_PEDAL=TRUE
DDEFS += -DEFI_AC_PRESSURE_FAN=TRUE
DDEFS += -DEFI_OFF_IDLE_RPM_ADDER=TRUE
DDEFS += -DEFI_LUA_LIMITER=TRUE
