// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/alphax-s550-pnp/connectors/custom_firmware.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char* getBoardSpecificPinName(brain_pin_e brainPin) {
	switch (brainPin) {
		case Gpio::A7:
			return "IMRC 2";
		case Gpio::B0:
			return "Fan 2";
		case Gpio::B1:
			return "Starter Relay";
		case Gpio::B14:
			return "CAM4 Bank2 Intake (PB14, via MAX9924)";
		case Gpio::B8:
			return "Injector 1";
		case Gpio::B9:
			return "Injector 5";
		case Gpio::C13:
			return "Injector 4";
		case Gpio::C4:
			return "Main Relay";
		case Gpio::C5:
			return "IMRC 1";
		case Gpio::C6:
			return "VVT 3 (Bank2 Exhaust)";
		case Gpio::C7:
			return "VVT 4 (Bank2 Intake)";
		case Gpio::C8:
			return "VVT 1 (Bank1 Exhaust)";
		case Gpio::C9:
			return "VVT 2 (Bank1 Intake)";
		case Gpio::D10:
			return "DPO 2";
		case Gpio::D14:
			return "Clutch Down Switch";
		case Gpio::D2:
			return "Start Autostart";
		case Gpio::D3:
			return "Shift Progress";
		case Gpio::D4:
			return "Brake Switch 2";
		case Gpio::D5:
			return "Start Request";
		case Gpio::D6:
			return "Reverse Switch";
		case Gpio::D7:
			return "Ignition 7";
		case Gpio::D8:
			return "DPO 1";
		case Gpio::D9:
			return "Tachometer Output";
		case Gpio::E0:
			return "ETB2 Disable";
		case Gpio::E1:
			return "ETB2 Direction";
		case Gpio::E10:
			return "Fuel FSO / PWR EN";
		case Gpio::E11:
			return "Alternator Control";
		case Gpio::E12:
			return "Fuel Pump Relay";
		case Gpio::E13:
			return "AC Clutch Relay";
		case Gpio::E14:
			return "Fan 1 Relay";
		case Gpio::E2:
			return "Injector 2";
		case Gpio::E3:
			return "Injector 7";
		case Gpio::E4:
			return "Injector 3";
		case Gpio::E5:
			return "Injector 6";
		case Gpio::E6:
			return "Injector 8";
		case Gpio::E7:
			return "Warn LED";
		case Gpio::E8:
			return "Error LED";
		case Gpio::E9:
			return "Brake Switch 1";
		case Gpio::F12:
			return "Ignition 2";
		case Gpio::F13:
			return "Ignition 3";
		case Gpio::F14:
			return "Ignition 1";
		case Gpio::F15:
			return "Ignition 4";
		case Gpio::F2:
			return "ADC MUX Select (PF2)";
		case Gpio::G0:
			return "Comms LED";
		case Gpio::G1:
			return "Run LED";
		case Gpio::G10:
			return "Ignition 5";
		case Gpio::G11:
			return "Ignition 8";
		case Gpio::G12:
			return "Clutch Up Switch";
		case Gpio::G13:
			return "Oil Level Switch";
		case Gpio::G2:
			return "Purge Solenoid";
		case Gpio::G3:
			return "Cutout Control";
		case Gpio::G4:
			return "Diff Pump Speed";
		case Gpio::G5:
			return "Vent Solenoid";
		case Gpio::G7:
			return "GENLI";
		case Gpio::G9:
			return "Ignition 6";
		case Gpio::H10:
			return "CAM2 Bank1 Intake (PH10, Hall)";
		case Gpio::H11:
			return "CAM1 Bank1 Exhaust (PH11, Hall)";
		case Gpio::H12:
			return "Boost Solenoid";
		case Gpio::H6:
			return "CAM3 Bank2 Exhaust (PH6, via MAX9924)";
		case Gpio::H7:
			return "Crankshaft Sensor (PH7, via MAX9924)";
		case Gpio::H8:
			return "Flex Fuel Sensor (PH8)";
		case Gpio::H9:
			return "VSS Vehicle Speed (PH9)";
		case Gpio::I4:
			return "ETB1 Disable";
		case Gpio::I5:
			return "ETB1 Direction";
		case Gpio::I6:
			return "ETB2 PWM";
		case Gpio::I7:
			return "ETB1 PWM";
		default:
			return nullptr;
	}
	return nullptr;
}
