// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/protorico-econoline/connectors/connectors.yaml
#pragma once

Gpio GENERATED_OUTPUTS[] = {
	Gpio::H144_IGN_1, // Ignition Coil 1
	Gpio::H144_IGN_2, // Ignition Coil 2
	Gpio::H144_IGN_3, // Ignition Coil 3
	Gpio::H144_IGN_4, // Ignition Coil 4
	Gpio::H144_IGN_5, // Ignition Coil 5
	Gpio::H144_IGN_6, // Ignition Coil 6
	Gpio::H144_IGN_7, // Ignition Coil 7
	Gpio::H144_IGN_8, // Ignition Coil 8
	Gpio::D3, // Injector 1
	Gpio::A9, // Injector 2
	Gpio::D11, // Injector 3
	Gpio::D10, // Injector 4
	Gpio::D2, // Injector 5
	Gpio::A8, // Injector 6
	Gpio::D15, // Injector 7
	Gpio::D12, // Injector 8
	Gpio::D7, // EGR Solenoid
	Gpio::E8, // TCI Control
	Gpio::A10, // IMRC Control
	Gpio::B14, // Fuel Pump Relay
	Gpio::B15, // Line Pressure Solenoid
	Gpio::A15, // O2 Sensor Heater
	Gpio::C11, // Torque Lockup Driver
	Gpio::C12, // TLS115 Power Good (TLS115_PG)
	Gpio::C10, // Purge Solenoid
	Gpio::H144_OUT_PWM1, // Idle Control
	Gpio::H144_OUT_PWM2, // A/C Clutch
	Gpio::H144_OUT_PWM3, // Tachometer Output
	Gpio::H144_OUT_PWM4, // Check Engine Light
	Gpio::H144_OUT_PWM5, // Solenoid A
	Gpio::H144_OUT_PWM6, // Solenoid B
// "Ignition Coil 1",
// "Ignition Coil 2",
// "Ignition Coil 3",
// "Ignition Coil 4",
// "Ignition Coil 5",
// "Ignition Coil 6",
// "Ignition Coil 7",
// "Ignition Coil 8",
// "Injector 1",
// "Injector 2",
// "Injector 3",
// "Injector 4",
// "Injector 5",
// "Injector 6",
// "Injector 7",
// "Injector 8",
// "EGR Solenoid",
// "TCI Control",
// "IMRC Control",
// "Fuel Pump Relay",
// "Line Pressure Solenoid",
// "O2 Sensor Heater",
// "Torque Lockup Driver",
// "TLS115 Power Good (TLS115_PG)",
// "Purge Solenoid",
// "Idle Control",
// "A/C Clutch",
// "Tachometer Output",
// "Check Engine Light",
// "Solenoid A",
// "Solenoid B",
}
