// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/protorico-econoline/connectors/connectors.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char* getBoardSpecificPinName(brain_pin_e brainPin) {
	switch (brainPin) {
		case Gpio::A10:
			return "IMRC Control";
		case Gpio::A15:
			return "O2 Sensor Heater";
		case Gpio::A8:
			return "Injector 6";
		case Gpio::A9:
			return "Injector 2";
		case Gpio::B14:
			return "Fuel Pump Relay";
		case Gpio::B15:
			return "Line Pressure Solenoid";
		case Gpio::B8:
			return "Ignition Coil 6";
		case Gpio::B9:
			return "Ignition Coil 7";
		case Gpio::C10:
			return "Purge Solenoid";
		case Gpio::C11:
			return "Torque Lockup Driver";
		case Gpio::C12:
			return "TLS115 Power Good (TLS115_PG)";
		case Gpio::C13:
			return "Ignition Coil 1";
		case Gpio::C6:
			return "A/C Clutch";
		case Gpio::C7:
			return "Tachometer Output";
		case Gpio::C8:
			return "Check Engine Light";
		case Gpio::C9:
			return "Solenoid A";
		case Gpio::D10:
			return "Injector 4";
		case Gpio::D11:
			return "Injector 3";
		case Gpio::D12:
			return "Injector 8";
		case Gpio::D13:
			return "Idle Control";
		case Gpio::D14:
			return "Solenoid B";
		case Gpio::D15:
			return "Injector 7";
		case Gpio::D2:
			return "Injector 5";
		case Gpio::D3:
			return "Injector 1";
		case Gpio::D7:
			return "EGR Solenoid";
		case Gpio::E0:
			return "EVAP Sensor/Input";
		case Gpio::E1:
			return "Aux Solenoid/Input";
		case Gpio::E12:
			return "Crank Trigger";
		case Gpio::E13:
			return "Cam Position";
		case Gpio::E14:
			return "Digital Input 3";
		case Gpio::E15:
			return "Digital Input 4";
		case Gpio::E2:
			return "Ignition Coil 5";
		case Gpio::E3:
			return "Ignition Coil 4";
		case Gpio::E4:
			return "Ignition Coil 3";
		case Gpio::E5:
			return "Ignition Coil 2";
		case Gpio::E6:
			return "Ignition Coil 8";
		case Gpio::E8:
			return "TCI Control";
		default:
			return nullptr;
	}
	return nullptr;
}
